### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Tymski** [adamvoss/vscode-languagetool#15]
I installed languagetool and english support, but I have no idea how to run the check?
I tried searching for "check" and "language", "english", "grammar" commands and so on but no luck for me.
I even tried changing programming language to english lol.
No info in the readme, no docs...
That should be like second thing in the readme

**Comment by StefanoCecere** [comment]
i agree.. total lack of readme on minimal use of this tool
disinstalling it

**Comment by adamvoss** [comment]
As with most similar Visual Studio Code extensions, behavior is automatic.  You open up a file type that is supported by the extension (documented in the README) and squiggles should appear under grammar issues.

**Comment by StefanoCecere** [comment]
ahh thank you @adamvoss it seems it doesn't work for me, then!

**Comment by Tymski** [comment]
Fix the readme then. First of all:
**plaintext** or cleartext is unencrypted information
**plain text** is the data (e.g. file contents) that represent only characters of readable material

And second of all
Add: "Works only in .txt and .md files" 
And that isn't optimal that you have to cut text from a file and paste it in to md file and then paste it back. The whole point of installing this kind of extension is to use it in place...

**Comment by bulfonjf** [comment]
> 
> 
> i agree.. total lack of readme on minimal use of this tool
> disinstalling it

Do you have Java 8 on your computer?

> 
> 
> ahh thank you @adamvoss it seems it doesn't work for me, then!

Do you have Java 8 installed on your computer?

> 
> 
> ahh thank you @adamvoss it seems it doesn't work for me, then!

I had the same problem, but then I read the readme file and saw that Java 8+ was required and that it was not installed on my computer. That solves my problem.
